logging:
  level:
    org.hibernate.type: TRACE

spine:
  web:
    open-api:
      title: '@project.parent.name@'
      description: '@project.parent.description@'
      version: '@project.parent.version@'

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hotels;MODE=PostgreSQL
    username: konekt-foundation
    password: fake-password

    hikari:
      maximum-pool-size: 10
      connectionTimeout: 30000
      minimumIdle: 1
      idleTimeout: 30000
      maxLifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy

  liquibase:
    enabled: true
    change-log: classpath:database/changelog/hotels-changelog-master.xml
